nomes = [
"Alysson Pink ❌", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅", "Alysson Pink ✅"
    ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"", ""Alysson Pink ❌"",
    "Arthur ✅",
    "Balbino ❌", "Balbino ✅", "Balbino ✅",
    "Bidu ✅", "Bidu ✅", "Bidu ✅",
    "Breno ❌",
    "Christopher ✅", "Christopher ❌", "Christopher ❌",
    "Elvinho ❌", "Elvinho ❌",
    "Felipe Melo ❌", "Felipe Melo ✅",
    "Gabriel ✅", "Gabriel ✅",
    "Grimauro ❌", "Grimauro ❌", "Grimauro ❌", "Grimauro ✅", "Grimauro ✅", "Grimauro ✅", "Grimauro ✅",
    'Henrique Souza ❌',
    "Ícaro ❌", "Ícaro ✅", "Ícaro ✅", "Ícaro ✅", "Ícaro ❌",
    "Jackson ❌", "Jackson ✅", "Jackson ❌", "Jackson ❌", "Jackson ✅", "Jackson ✅", "Jackson ✅",
    "Jefferson ❌", "Jefferson ✅", "Jefferson ✅", "Jefferson ✅",
    "Jorge ❌", "Jorge ❌",
    "Juninho ❌", "Juninho ❌", "Juninho ✅", "Juninho ✅", "Juninho ✅", "Juninho ✅", "Juninho ✅", "Juninho ✅", "Juninho ✅", "Juninho ✅",
    "Lazaro ❌", "Lazaro ✅",
    "Leo ❌", "Leo ✅", "Leo ✅", "Leo ❌",
    "Lucas Paranhos ❌", 'Lucas Paranhos ❌',
    "Nagibio ❌",
    "Nagibio ✅", "Nagibio ✅",
    "Neto ❌", "Neto ✅", "Neto ✅", "Neto ✅", "Neto ✅", "Neto ✅",
    "Pedro ❌", "Pedro ❌", "Pedro ❌",
    "Pou ✅", "Pou ✅",
    "Reynods ✅",
    "Ronaldinho ✅", "Ronaldinho ✅", "Ronaldinho ✅",
    "Sérgio ❌", "Sérgio ❌", "Sérgio ✅", "Sérgio ✅", "Sérgio ✅", "Sérgio ✅", "Sérgio ✅", "Sérgio ✅", "Sérgio ✅",
    "Teffinho ✅", "Teffinho ✅",
    "Teteca ❌", "Teteca ❌",
    'Tulio B. ✅',
    'Winnicius C. ❌', "Winnicius C. ✅", "Winnicius C. ✅", "Winnicius C. ✅", "Winnicius C. ✅", "Winnicius C. ✅", "Winnicius C. ✅", "Winnicius C. ✅", "Winnicius C. ✅",
    'Xand ❌', 'Xand ❌', 'Xand ❌', 'Xand ✅'
]
