from collections import defaultdict

# Lista de nomes com os respectivos status
nomes = [
    'Arthur ✅',
    'Balbino ❌',
    'Breno ❌',
    'Cadu',
    'Cadu ✅',
    'Cadu ✅',
    'Cadu ❌',
    'Christopher',
    'Christopher',
    'Christopher ✅',
    'Christopher ✅',
    'Claudino',
    'Claudino ✅',
    'Claudino ✅',
    'Claudino ✅',
    'Claudino ✅',
    'Claudino ✅',
    'Claudino ✅',
    'Claudino ✅',
    'Claudino ❌',
    'Elvis',
    'Farneze ❌',
    'Gabriel',
    'Grimauro',
    'Grimauro',
    'Grimauro',
    'Grimauro ✅',
    'Grimauro ✅',
    'Grimauro ❌',
    'Grimauro',
    'Grimauro ✅',
    'Grimauro ✅',
    'Ícaro',
    'Ícaro',
    'Ícaro ✅',
    'Ícaro ✅',
    'Ícaro ✅',
    'Ícaro ❌',
    'Márcio ✅',
    'Jefferson',
    'Jefferson',
    'Jefferson',
    'Jefferson ✅',
    'Jefferson ✅',
    'Jefferson ✅',
    'Jefferson ❌',
    'Jefferson ❌',
    'João',
    'João ❌',
    'Juninho',
    'Juninho',
    'Juninho',
    'Juninho ✅',
    'Juninho ✅',
    'Juninho ✅',
    'Juninho ✅',
    'Juninho ✅',
    'Juninho ✅',
    'Juninho ✅',
    'Juninho ✅',
    'Lázaro ✅',
    'Léo',
    'Léo ✅',
    'Léo ✅',
    'Léo ✅',
    'Léo ✅',
    'Léo ✅',
    'Léo ✅',
    'Léo',
    'Léo',
    'Márcio',
    'Márcio',
    'Márcio ✅',
    'Márcio ✅',
    'Márcio ✅',
    'Nagibio ✅',
    'Nagibio ✅',
    'Neto',
    'Neto',
    'Neto',
    'Neto ✅',
    'Neto ✅',
    'Neto ❌',
    'Neto ✅',
    'Neto ✅',
    'Rafa ✅',
    'Renan ✅',
    'Ronaldinho',
    'Ronaldinho ✅',
    'Ronaldinho ✅',
    'Ronaldinho ✅',
    'Ronaldinho ✅',
    'Sérgio',
    'Sérgio',
    'Sérgio',
    'Sérgio ✅',
    'Sérgio ✅',
    'Sérgio ✅',
    'Sérgio ✅',
    'Sérgio ✅',
    'Sérgio ✅',
    'Sérgio ✅',
    'Sérgio ❌',
    'Sérgio Vilar ✅',
    'Túlio',
    'Túlio ✅',
    'Túlio ✅',
    'Túlio ✅',
    'Túlio ❌',
    'Túlio ✅,'
    'Túlio ✅',
    'Xand',
    'Xand',
    'Xand',
    'Xand ✅',
    'Xand ✅',
    'Xand ❌',
    'Xand ✅',
    'Xandinho ❌',

]

# Dicionário para armazenar os pontos de cada nome
pontuacao = defaultdict(int)

# Contagem dos pontos
for nome in nomes:
    nome_ponto = nome.split(' ')[0]
    if "✅" in nome:
        pontuacao[nome_ponto] += 2
    elif "❌" in nome:
        pontuacao[nome_ponto] += 0
    else:
        pontuacao[nome_ponto] += 1

# Gerar o ranking
ranking = sorted(pontuacao.items(), key=lambda x: x[1], reverse=True)

# Imprimir o ranking
print("Ranking de frequencia dos diaristas:")
for posicao, (nome, pontos) in enumerate(ranking, start=1):
    print(f"{posicao}. {nome} - {pontos} pontos")
