mensalistas = [
    {'jogador': 'Albert', 'habilidade': 5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'sim'},
    {'jogador': 'Alysson Pink', 'habilidade': 3, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Betinho', 'habilidade': 4, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'diretor': 'sim'},
    {'jogador': 'Bidu', 'habilidade': 4, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Bruno Pessoa', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Dato', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Diego Rocha', 'habilidade': 4.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
    {'jogador': 'Eduardo', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
    {'jogador': 'Eric', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'diretor': 'sim'},
    {'jogador': 'Flávio', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Henrique Silva', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
    {'jogador': 'Kiel', 'habilidade': 5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Lucas Henrique', 'habilidade': 3, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Lucas Silveira', 'habilidade': 1, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Manga', 'habilidade': 4, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Marcelinho', 'habilidade': 4, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Niclaudio', 'habilidade': 3, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Paulo Thiago', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
    {'jogador': 'Raphael Borges', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
    {'jogador': 'Teixa', 'habilidade': 3, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Thiago Alemão', 'habilidade': 2, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Victor Assis', 'habilidade': 3, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Victor Chaves', 'habilidade': 3, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'sim'},
    {'jogador': 'Vinicius', 'habilidade': 5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Vitor Salgado', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
]

diaristas = [
    {'jogador': 'Balbino', 'habilidade': 2.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Chistopher', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Claudino', 'habilidade': 5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Dudu', 'habilidade': 5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Duduzinho', 'habilidade': 5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Elvis', 'habilidade': 4, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Felipe Melo', 'habilidade': 3, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Gabriel', 'habilidade': 2, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Grimauro', 'habilidade': 2.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Henrique Souza', 'habilidade': 4, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Ícaro Feitosa', 'habilidade': 5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Italo', 'habilidade': 4, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Jackson', 'habilidade': 4, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Jefferson', 'habilidade': 4, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
    {'jogador': 'Jorge', 'habilidade': 3, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Juninho', 'habilidade': 3.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Lázaro', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'diretor': 'nao'},
    {'jogador': 'Leo Albuquerque', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Lucas Paranhos', 'habilidade': 3.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Marcos S.', 'habilidade': 3.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Matheus', 'habilidade': 4.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Nagibio', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Nestor', 'habilidade': 4, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Neto', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Pablo', 'habilidade': 3, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Pedro', 'habilidade': 4.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'atacante', 'diretor': 'nao'},
    {'jogador': 'Pou', 'habilidade': 2.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Rafa Ribeiro', 'habilidade': 3, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'sim'},
    {'jogador': 'Renan', 'habilidade': 4, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Ronaldinho', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
    {'jogador': 'Teffinho', 'habilidade': 4, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Teteca', 'habilidade': 3, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Tiago César', 'habilidade': 3, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Vinicinho', 'habilidade': 4, 'posicao_primaria': 'qualquer', 'posicao_secundaria': 'nenhum', 'diretor': 'nao'},
    {'jogador': 'Xandinho', 'habilidade': 1, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'diretor': 'nao'},
]
