lista_jogadores = [
        {'nome': 'Lauber', 'habilidade': 2.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Filipinho', 'habilidade': 5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Claudino', 'habilidade': 4.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Flávio Ribeiro', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Maradona', 'habilidade': 5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
        {'nome': 'Thiago Alemão', 'habilidade': 2, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Paullo Silva', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
        {'nome': 'Alysson Pink', 'habilidade': 3, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Bruno Pessoa', 'habilidade': 4.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'adm': True},
        {'nome': 'Elvis', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': False},
        {'nome': 'Marcio', 'habilidade': 3, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
        {'nome': 'Raphael B.', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
        {'nome': 'Xandinho', 'habilidade': 1, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Juninho', 'habilidade': 3, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Dato', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Paulo Thiago', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
        {'nome': 'Biro', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Ronaldinho', 'habilidade': 3, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
        {'nome': 'Sérgio Falcão', 'habilidade': 2.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Pedro Barbeiro', 'habilidade': 2, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Vitinho', 'habilidade': 3, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Marcos S.', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
        {'nome': 'Grimauro', 'habilidade': 2, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Isaias', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Thiago Sultanum', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Beu', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Teixa', 'habilidade': 2.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'adm': False},
        {'nome': 'Gabriel', 'habilidade': 2, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
        {'nome': 'Carlinhos', 'habilidade': 3, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
        {'nome': 'Stive', 'habilidade': 2.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'nenhum', 'adm': False},
]
