var jogadores = [
  { nome: "Albert", habilidade: 5 },
  { nome: "Betinho", habilidade: 4 },
  { nome: "Bruno Pessoa", habilidade: 3.5 },
  { nome: "Diego Rocha", habilidade: 4 },
  { nome: "Eduardo", habilidade: 3.5 },
  { nome: "Eric", habilidade: 3.5 },
  { nome: "Flávio", habilidade: 3.5 },
  { nome: "Henrique Silva", habilidade: 3.5 },
  { nome: "Jorge", habilidade: 2.5 },
  { nome: "Kiel", habilidade: 4.5 },
  { nome: "Lucas Henrique", habilidade: 2.5 },
  { nome: "Lucas Silveira", habilidade: 1 },
  { nome: "Manga", habilidade: 4 },
  { nome: "Marcelinho", habilidade: 4 },
  { nome: "Marquinhos S.", habilidade: 3.5 },
  { nome: "Matheus Ureia", habilidade: 4 },
  { nome: "Niclaudio", habilidade: 2 },
  { nome: "Paulo Thiago", habilidade: 4.5 },
  { nome: "Raphael Borges", habilidade: 4 },
  { nome: "Teixa", habilidade: 2.5 },
  { nome: "Tiago Alemão", habilidade: 2 },
  { nome: "Victor Assis", habilidade: 3 },
  { nome: "Victor Cabeça", habilidade: 3 },
  { nome: "Vinícius", habilidade: 5 },
  { nome: "Vitor Salgado", habilidade: 4 },
  { nome: "Balbino", habilidade: 2.5 },
  { nome: "Bidu", habilidade: 3.5 },
  { nome: "Dato", habilidade: 3.5 },
  { nome: "Edmundo", habilidade: 3 },
  { nome: "Elvinho", habilidade: 4 },
  { nome: "Felipe Melo", habilidade: 3 },
  { nome: "Gabriel Ferreira", habilidade: 2 },
  { nome: "Gil", habilidade: 4 },
  { nome: "Ícaro", habilidade: 5 },
  { nome: "Ítalo", habilidade: 4.5 },
  { nome: "Jackson", habilidade: 3.5 },
  { nome: "Jefferson", habilidade: 4 },
  { nome: "Juninho", habilidade: 3.5 },
  { nome: "Pou", habilidade: 3 },
  { nome: "Renan", habilidade: 4.5 },
  { nome: "Ronaldinho", habilidade: 3 },
  { nome: "Teteca", habilidade: 4 },
  { nome: "Winnicius C.", habilidade: 5 },
  { nome: "Alysson Pink", habilidade: 3 },
  { nome: "Vinicinho ", habilidade: 4.5 },
  { nome: "Lázaro ", habilidade: 3 },
  { nome: "Pedro ", habilidade: 4 },
  { nome: "Emerson", habilidade: 3 },
  { nome: "Grimauro", habilidade: 2 },
  { nome: "Rafa Ribeiro", habilidade: 3 },
  { nome: "Stefersson", habilidade: 4 },
];

export default jogadores;