# Generated by Django 5.0.1 on 2024-02-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('habilidade', models.FloatField()),
                ('adm', models.BooleanField(default=False)),
                ('posicao_primaria', models.CharField(max_length=50)),
                ('posicao_secundaria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
