mensalistas = [
    {'nome': 'Albert', 'habilidade': 5.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': True},
    {'nome': 'Betinho', 'habilidade': 4.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': True},
    {'nome': 'Bidu', 'habilidade': 4.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Bruno Pessoa', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Dato', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Diego Rocha', 'habilidade': 4.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
    {'nome': 'Eduardo', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
    {'nome': 'Eric ', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': None, 'adm': True},
    {'nome': 'Flávio', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Henrique Silva', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
    {'nome': 'Kiel', 'habilidade': 5.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Lucas Henrique', 'habilidade': 3.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Lucas Silveira', 'habilidade': 1.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Manga ', 'habilidade': 4.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Marcelinho', 'habilidade': 4.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Niclaudio', 'habilidade': 3.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Paulo Thiago', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
    {'nome': 'Raphael Borges', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
    {'nome': 'Teixa', 'habilidade': 3.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Thiago Alemão', 'habilidade': 2.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Victor Assis', 'habilidade': 3.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Victor Chaves', 'habilidade': 3.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': True},
    {'nome': 'Vinicius', 'habilidade': 5.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Vitor Salgado', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
]

diaristas = [
    {'nome': 'Alysson Pink', 'habilidade': 3.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Balbino', 'habilidade': 2.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Chistopher', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Claudino', 'habilidade': 5.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Dudu', 'habilidade': 5.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Duduzinho', 'habilidade': 5.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Elvis', 'habilidade': 4.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Felipe Melo', 'habilidade': 3.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Gabriel', 'habilidade': 2.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Grimauro', 'habilidade': 2.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Henrique Souza', 'habilidade': 4.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Ícaro Feitosa', 'habilidade': 5.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Italo', 'habilidade': 4.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Jackson', 'habilidade': 4.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Jefferson', 'habilidade': 4.0, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
    {'nome': 'Jorge', 'habilidade': 3.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Juninho', 'habilidade': 3.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Lázaro', 'habilidade': 3.5, 'posicao_primaria': 'meia', 'posicao_secundaria': 'zagueiro', 'adm': False},
    {'nome': 'Leo Albuquerque', 'habilidade': 3.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Lucas Paranhos', 'habilidade': 3.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Marcos S.', 'habilidade': 3.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Matheus', 'habilidade': 4.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Nagibio', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Nestor', 'habilidade': 4.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Neto', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Pablo', 'habilidade': 3.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Pedro', 'habilidade': 4.5, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'atacante', 'adm': False},
    {'nome': 'Pou', 'habilidade': 2.5, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Rafa Ribeiro', 'habilidade': 3.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': True},
    {'nome': 'Renan', 'habilidade': 4.0, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Ronaldinho', 'habilidade': 3.5, 'posicao_primaria': 'atacante', 'posicao_secundaria': 'meia', 'adm': False},
    {'nome': 'Teffinho', 'habilidade': 4.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Teteca', 'habilidade': 3.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Tiago César', 'habilidade': 3.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Vinicinho', 'habilidade': 4.0, 'posicao_primaria': 'qualquer', 'posicao_secundaria': None, 'adm': False},
    {'nome': 'Xandinho', 'habilidade': 1.0, 'posicao_primaria': 'zagueiro', 'posicao_secundaria': 'meia', 'adm': False},
]