var jogadores = [
  {
    nome: " ",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Albert",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Betinho",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Bruno Pessoa",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Diego Rocha",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Eduardo",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Eric",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Flávio",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Henrique Silva",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Jorge",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Kiel",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Lucas Henrique",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Lucas Silveira",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Manga",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Marcelinho",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Marquinhos S.",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Matheus Ureia",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Niclaudio",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Paulo Thiago",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Raphael Borges",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Teixa",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Tiago Alemão",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Victor Assis",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Victor Cabeça",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Vinícius",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Vitor Salgado",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Balbino",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Bidu",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Dato",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Edmundo",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Elvinho",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Felipe Melo",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Gabriel Ferreira",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Gil",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Ícaro",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Ítalo",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Jackson",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Jefferson",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Juninho",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Pou",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Renan",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Ronaldinho",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Teteca",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Winnicius C.",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Alysson Pink",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Vinicinho ",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Lázaro ",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Pedro ",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Emerson",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
];

var goleiros = [
  {
    nome: "Borel",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Gustavo",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Heverton",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Japa",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Leandro",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Matheus",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Riva",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
  {
    nome: "Uili",
    gol: 0,
    finalizacaoTrave: 0,
    finalizacaoDefendida: 0,
    finalizacaoFora: 0,
    assistencia: 0,
    lancamentoLongo: 0,
    desarme: 0,
    faltaSofrida: 0,
    penaltiSofrido: 0,
    jogoSemSofrerGol: 0,
    defesa: 0,
    defesaPenalti: 0,
    golSofrido: 0,
    faltaCometida: 0,
    golContra: 0,
    cartaoAmarelo: 0,
    cartaoVermelho: 0,
    penaltiPerdido: 0,
    penaltiCometido: 0,
  },
];

// Exporta os jogadores e goleiros para uso no HTML
if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    jogadores: jogadores,
    goleiros: goleiros,
  };
}